dist: xenial
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libwxgtk3.0-dev libgtk2.0-dev gettext autopoint libasound2-dev alsa-utils alsa-oss
    - git show -s --format="#define REV_LONG \"%H\"%n#define REV_TIME \"%cd\"%n" | tee ./src/RevisionIdent.h
    - FLAGS="-std=gnu++11"
    - export CFLAGS="$CFLAGS $FLAGS"
    - export CXXFLAGS="$CXXFLAGS $FLAGS"
    - g++ --version
language:
    - cpp
script:
    - mkdir build
    - cd build
    - time ../configure && time make modules && time make -j2
